# Generated by Django 3.0.5 on 2020-05-15 19:53

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.CharField(max_length=300)),
                ('image_1', models.CharField(max_length=300)),
                ('image_2', models.CharField(max_length=300)),
                ('image_3', models.CharField(max_length=300)),
                ('image_4', models.CharField(max_length=300)),
                ('image_5', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('size', models.CharField(default='none', max_length=100)),
                ('category', models.CharField(choices=[('Accessories', 'Accessories'), ('Outerwear', 'Outerwear'), ('Sale', 'Sale'), ('Tees', 'Tees'), ('Shirts', 'Shirts'), ('Sweatshirts', 'Sweatshirts'), ('Jackets', 'Jackets'), ('Shoes', 'Shoes'), ('Bottoms', 'Bottoms')], default='Blank=True', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('item_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('image_1', models.CharField(default='', max_length=300)),
                ('slug', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('discount_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('category', models.CharField(choices=[('Accessories', 'Accessories'), ('Outerwear', 'Outerwear'), ('Sale', 'Sale'), ('Tees', 'Tees'), ('Shirts', 'Shirts'), ('Sweatshirts', 'Sweatshirts'), ('Jackets', 'Jackets'), ('Shoes', 'Shoes'), ('Bottoms', 'Bottoms')], max_length=200)),
                ('description', models.TextField()),
                ('image_1', models.CharField(max_length=300)),
                ('image_2', models.CharField(max_length=300)),
                ('image_3', models.CharField(max_length=300)),
                ('image_4', models.CharField(max_length=300)),
                ('image_5', models.CharField(max_length=300)),
                ('size', multiselectfield.db.fields.MultiSelectField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13')], max_length=100)),
                ('color', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.CharField(default='', max_length=6)),
                ('order_item_list', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shop.OrderItem')),
                ('shipping_address', models.CharField(default='', max_length=300)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=300)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
    ]
