# Generated by Django 3.0.5 on 2020-05-16 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200515_2256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
