# Generated by Django 3.0.5 on 2020-05-16 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default='', max_length=6)),
                ('shipping_address', models.CharField(default='', max_length=300)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=300)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('order_item_list', models.ManyToManyField(blank=True, to='shop.OrderItem')),
            ],
        ),
    ]
