# Generated by Django 3.0.5 on 2020-05-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_item_list',
            field=models.ManyToManyField(blank=True, null=True, to='shop.OrderItem'),
        ),
    ]
