# Generated by Django 3.0.5 on 2020-05-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200516_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
