# Generated by Django 3.0.5 on 2020-05-16 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_item_list',
        ),
        migrations.AddField(
            model_name='order',
            name='order_item_list',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.OrderItem'),
        ),
    ]
