# Generated by Django 3.0.5 on 2020-05-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200516_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_item_list',
        ),
        migrations.AddField(
            model_name='order',
            name='order_item_list',
            field=models.ManyToManyField(blank=True, default='', null=True, to='shop.OrderItem'),
        ),
    ]
