# Generated by Django 3.0.5 on 2020-05-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200516_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='slug',
            field=models.CharField(default='', max_length=6),
        ),
    ]
