# Generated by Django 3.0.5 on 2020-05-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200516_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image_link',
            field=models.IntegerField(default=0),
        ),
    ]
