# Generated by Django 3.0.5 on 2020-05-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_orderitem_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking',
            field=models.CharField(default='', max_length=300),
        ),
    ]
