# Generated by Django 3.0.5 on 2020-05-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Shipped', 'Shipped'), ('Issues', 'Issues'), ('Refunded', 'Refunded')], default='Not Started', max_length=200),
        ),
    ]
