# Generated by Django 2.2 on 2020-05-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20200517_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.CharField(choices=[('Not On Sale', 'Not On Sale'), ('On Sale', 'On Sale')], default='Not On Sale', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Outerwear', 'Outerwear'), ('Tees', 'Tees'), ('Shirts', 'Shirts'), ('Sweatshirts', 'Sweatshirts'), ('Jackets', 'Jackets'), ('Shoes', 'Shoes'), ('Bottoms', 'Bottoms')], default='Blank=True', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Outerwear', 'Outerwear'), ('Tees', 'Tees'), ('Shirts', 'Shirts'), ('Sweatshirts', 'Sweatshirts'), ('Jackets', 'Jackets'), ('Shoes', 'Shoes'), ('Bottoms', 'Bottoms')], max_length=200),
        ),
    ]
